### ISSUE TITLE
Is this projet still maintained?

### ISSUE THREAD

**Issue by jorge-d** [ArcticCore/arcticcoin#5]
Hi,

I'm considering setting a few masternodes, I would like to know if you are still maintaining this projet considering the lack of activity?

Cheers,

**Comment by squirelo** [comment]
Yes, there is a strong community and 300+ masternode running right now. The dev has changed in march, and a new owner is handling the project.

Feel free to join the forum, and please share some good vibes to help us bring this wonderful coin where it deserves to be.

**Comment by jorge-d** [comment]
Alright, thanks ! Gonna run a few of them then
