### ISSUE TITLE
Method not found (code -32601)

### ISSUE THREAD

**Issue by bapparabi** [ArcticCore/arcticcoin#6]
Hi i am trying to setup arcticcoin master node but when i tryt o pass this command

Code:

goldmine genkey

form this link

https://arcticcoin.org/en-EN/guides-goldmine

i am getting this error  " Method not found (code -32601) "

Do you any one what is issue and how to solve this iisue

**Comment by smorlock** [comment]
Try "goldminenode" instead of "goldmine".  The instructions are incorrect.
